### ISSUE TITLE
Second gem doesn't accept anything but a literal "DRZW"

### ISSUE THREAD

**Issue by gregghz** [alejandrolujan/scalaquest-bugs#10] opened 2018-02-17 19:06 UTC
I think it should allow any expression that evaluates to "DRZW" but it seems to require the literal String. It would be nice to be able to experiment with different ways to come to a solution. Other problems on this gem have the same issue. Maybe the issue is the wording of the problem. Instead of "A string..." maybe "The literal string value ..."

![image](https://user-images.githubusercontent.com/220801/36344622-8702a01c-13da-11e8-8639-16f9437cc608.png)

**Comment by egp** [comment] 2018-02-19 05:56
Yeah I tried that myself and had to resort to the literal instead

**Comment by alejandrolujan** [comment] 2018-02-24 21:31
This a great point, Gregg, thanks for the feedback.

One thing to consider is that the game is mainly aimed at devs who have little or zero experience with the language. So, while they may come up with different solutions, they'll likely not involve such an advanced expression as what you came up with :)

However, the point still stands. I'll mark this as a duplicate of https://github.com/alejandrolujan/scalaquest-bugs/issues/14 since that is a more general conversation that includes this and several other challenges.

I'm also archiving this issue, feel free to add to the discussion on https://github.com/alejandrolujan/scalaquest-bugs/issues/14.

**Comment by alejandrolujan** [comment] 2018-02-24 21:31
Included in the discussion of https://github.com/alejandrolujan/scalaquest-bugs/issues/14

**Closed by alejandrolujan** 2018-02-24 21:31 UTC
Labels: duplicate
